import '/app/[lng]/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[var(--dash-theme)]">{children}</body>
    </html>
  )
}
